// 2026-05 用户："去掉目前的河，用新做的河来代替" — qinlingHydrography 不
// 再 hand-type 任何 feature。所有水系 features 都从 src/game/data/qinlingNeRivers.js
// 派生 (auto-generated by scripts/build-qinling-hydrography-from-ne.mjs)，
// 数据源跟 china-rivers-prototype.html 同一份 (major-rivers.json + OSM Overpass)。
//
// 当前 modern hydrography 直接反映扩区后的主河集合：
//   - 旧 slice 主干：渭河 / 汉水 / 嘉陵江
//   - 南扩新增：长江 / 金沙江 / 岷江 / 乌江 / 沱江
//   - 小支流仍不 hand-type；需要时再通过 OSM/人工补洞回填。
//
// 跑 \`node scripts/build-qinling-hydrography-from-ne.mjs\` 重新生成
// qinlingNeRivers，再跑 \`npm run qinling:dem:build-real\` 让 DEM 雕刻同步。

import { qinlingNeRivers } from "./data/qinlingNeRivers.js";

// rank → kind ("river" / "stream") 映射. NE 主干 = river, 小灌渠 = stream.
function kindForRank(rank) {
  return rank >= 3 ? "stream" : "river";
}

// 大致 city / pass relations。等数据稳定后再补全；现在只填历史最重要的几条。
const RELATIONS_BY_ID = {
  "river-changjiang": ["city-yibin"],
  "river-jinshajiang": ["city-yibin"],
  "river-weihe": ["city-changan", "city-xianyang", "city-baoji-chencang"],
  "river-hanjiang": ["city-hanzhong", "road-jinniu-jianmen"],
  "river-jialingjiang": ["city-guangyuan", "city-zhaohua", "pass-jianmen"],
  "river-minjiang": ["city-yibin"],
  "river-wujiang": [],
  "river-tuojiang": [],
  "stream-baohe": ["road-baoxie", "military-shimen"],
  "river-neijiang": ["city-chengdu"]
};

const SOURCE_FOR_DATA = {
  "openstreetmap-overpass": { name: "openstreetmap-overpass", confidence: "high", verification: "external-vector" },
  "openstreetmap-overpass + manual bridge across 都江堰 dam, sorted N→S, densified ~2km": {
    name: "openstreetmap-overpass+manual-bridge",
    confidence: "high",
    verification: "external-vector"
  }
};
function sourceFor(entry) {
  if (entry.sourceData && SOURCE_FOR_DATA[entry.sourceData]) {
    return SOURCE_FOR_DATA[entry.sourceData];
  }
  return { name: "natural-earth-10m", confidence: "high", verification: "external-vector" };
}

// 把 qinlingNeRivers 里每个 entry 转成 HydrographyFeature.
const features = Object.entries(qinlingNeRivers).map(([id, entry]) => ({
  id,
  name: entry.name,
  displayName: entry.displayName ?? entry.name,
  aliases: entry.aliases ?? [],
  kind: kindForRank(entry.rank ?? 1),
  rank: entry.rank ?? 1,
  basin: entry.basin ?? entry.sourceBasin ?? "未分类",
  eraId: "modern",
  source: sourceFor(entry),
  relations: RELATIONS_BY_ID[id] ?? [],
  geometry: { points: entry.points }
}));

// 按 rank 升序 (主干在前) — 让 atlas 渲染顺序保持 main-first.
features.sort((a, b) => a.rank - b.rank);

export const qinlingModernHydrography = {
  schema: "visual-china.region-hydrography.v1",
  regionId: "qinling",
  eraId: "modern",
  basePolicy: "modern-hydrography",
  notes: [
    "Qinling slice rivers — auto-derived from src/game/data/qinlingNeRivers.js.",
    "Source: Natural Earth 10m rivers + OSM Overpass (public domain).",
    "Rebuild via: node scripts/build-qinling-hydrography-from-ne.mjs",
    `${features.length} features, all external-vector verified.`
  ],
  features
};
