// Tang 755 admin geography loader.
//
// Data source: CHGIS V6 (Harvard CGA + 复旦大学历史地理研究中心)
// Generated by: scripts/build-tang-admin-from-chgis.py
// Build:        python3 scripts/build-tang-admin-from-chgis.py
//
// 跟 POI registry 互补:
//   - POI registry (poiRegistry.generated.ts): 重点 POI 含 doc + tier, ~27 个
//   - Tang admin (此模块): 全唐 1470 县 + 339 州 + 121 州疆域 polygon, 来源 CHGIS
//
// 用法 (lazy load, fullscreen minimap 第一次开时 fetch):
//   const data = await loadTangAdmin();
//   for (const pgn of data.prefecturePolygons) { ... }

export interface TangAdminPoint {
  id?: number;
  nameCH: string;
  namePY: string;
  type?: string;
  typePY?: string;
  level?: string;
  modernLoc?: string;
  begYr: number;
  endYr: number;
  lat: number;
  lon: number;
}

export interface TangAdminPolygon {
  id?: number;
  nameCH: string;
  namePY: string;
  type?: string;
  typePY?: string;
  level?: string;
  begYr: number;
  endYr: number;
  /** GeoJSON-style nested arrays: [[ [lon, lat], ... ], holes...] */
  rings: [number, number][][];
}

export interface TangAdminBundle {
  counties: TangAdminPoint[];
  prefectures: TangAdminPoint[];
  prefecturePolygons: TangAdminPolygon[];
}

let cached: TangAdminBundle | null = null;
let inflight: Promise<TangAdminBundle> | null = null;

const BASE_URL = "/data/tang-755";

export async function loadTangAdmin(): Promise<TangAdminBundle> {
  if (cached) return cached;
  if (inflight) return inflight;
  inflight = (async () => {
    const [counties, prefectures, polygons] = await Promise.all([
      fetch(`${BASE_URL}/counties.json`).then((r) => r.json() as Promise<TangAdminPoint[]>),
      fetch(`${BASE_URL}/prefectures.json`).then((r) => r.json() as Promise<TangAdminPoint[]>),
      fetch(`${BASE_URL}/prefecture-polygons.json`).then((r) => r.json() as Promise<TangAdminPolygon[]>)
    ]);
    cached = {
      counties,
      prefectures,
      prefecturePolygons: polygons
    };
    return cached;
  })();
  return inflight;
}
